### ISSUE TITLE
Cannot find module 'bindings'

### ISSUE THREAD

**Issue by cheery** [mikeseven/node-webgl#23]
Cloned repo today and tried it, but it ended up like this:

<pre>cheery@ruttunen:~/node-webgl$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.0
gyp info using node@0.10.25 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cheery/node-webgl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cheery/.node-gyp/0.10.25/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cheery/.node-gyp/0.10.25',
gyp info spawn args   '-Dmodule_root_dir=/home/cheery/node-webgl',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/cheery/node-webgl/build'
  CXX(target) Release/obj.target/webgl/src/bindings.o
  CXX(target) Release/obj.target/webgl/src/image.o
  CXX(target) Release/obj.target/webgl/src/webgl.o
  SOLINK_MODULE(target) Release/obj.target/webgl.node
  SOLINK_MODULE(target) Release/obj.target/webgl.node: Finished
  COPY Release/webgl.node
make: Leaving directory `/home/cheery/node-webgl/build'
gyp info ok 
cheery@ruttunen:~/node-webgl$ node test/lesson02.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'bindings'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cheery/node-webgl/lib/webgl.js:1:89)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
cheery@ruttunen:~/node-webgl$ </pre>

**Comment by NickLatysh** [comment]
You can downgrade ? if use node 0.8.9  september 2015 version, you can make the module using the node-gyp

**Comment by mikeseven** [comment]
Not really. Your js code will continue working but internal changes between node 0.8 and 3+ are so big that it would be too painful to maintain.
Out of curiosity, why do u need to use such an outdated version of node?

--mike



On Wed, Dec 2, 2015 at 5:56 AM -0800, "NickLatysh" <notifications@github.com<mailto:notifications@github.com>> wrote:


You can downgrade ? if use node 0.8.9 september 2015 version, you can make the module using the node-gyp

-

**Comment by NickLatysh** [comment]
For whatever reasons, the garbage MSVC gives a lot of errors and does not
allow to install the module as expected. On GitHub to some projects in the
instructions given version that will suit most often have to do a fall.

--Nick

2015-12-03 0:18 GMT+05:00 m1k3 <notifications@github.com>:

> Not really. Your js code will continue working but internal changes
> between node 0.8 and 3+ are so big that it would be too painful to maintain.
> Out of curiosity, why do u need to use such an outdated version of node?
>
> --mike
>
>
>
> On Wed, Dec 2, 2015 at 5:56 AM -0800, "NickLatysh" <

**Comment by mikeseven** [comment]
Weird. Can you tell me more about your system? Nodejs version, OS version, msvc version...
We test node-webgl and node-glfw on mac, linux, windows. For windows, we use nodejs 4.x, latest Nan and bindings, latest release of glfw3, AntTweakBar, GLEW and latest AMD APP SDK or nvidia and respective drivers.

--mike



On Wed, Dec 2, 2015 at 10:30 PM -0800, "NickLatysh" <notifications@github.com<mailto:notifications@github.com>> wrote:

For whatever reasons, the garbage MSVC gives a lot of errors and does not
allow to install the module as expected. On GitHub to some projects in the
instructions given version that will suit most often have to do a fall.

--Nick

2015-12-03 0:18 GMT+05:00 m1k3 <notifications@github.com>:

> Not really. Your js code will continue working but internal changes
> between node 0.8 and 3+ are so big that it would be too painful to maintain.
> Out of curiosity, why do u need to use such an outdated version of node?
>
> --mike
>
>
>
> On Wed, Dec 2, 2015 at 5:56 AM -0800, "NickLatysh" <
> notifications@github.com<mailto:notifications@github.com>> wrote:
>
>
> You can downgrade ? if use node 0.8.9 september 2015 version, you can make
> the module using the node-gyp
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161300168>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161403717>
> .
>

-

**Comment by NickLatysh** [comment]
Mike, do not want to puff your brains out, now I'm distracted by other
things.

 Overall, these characteristics: win 8.1. , Nodejs 5.1 or 4.x, python 2.7,
and set msvs 2012

2015-12-03 21:38 GMT+05:00 m1k3 <notifications@github.com>:

> Weird. Can you tell me more about your system? Nodejs version, OS version,
> msvc version...
> We test node-webgl and node-glfw on mac, linux, windows. For windows, we
> use nodejs 4.x, latest Nan and bindings, latest release of glfw3,
> AntTweakBar, GLEW and latest AMD APP SDK or nvidia and respective drivers.
>
> --mike
>
>
>
> On Wed, Dec 2, 2015 at 10:30 PM -0800, "NickLatysh" <

**Comment by mikeseven** [comment]
Looks good. We don't try vs2012 but vs2015 though it should work.

Please copy the output of visual studio.

Thanks,

--mike



On Thu, Dec 3, 2015 at 7:16 PM -0800, "NickLatysh" <notifications@github.com<mailto:notifications@github.com>> wrote:

Mike, do not want to puff your brains out, now I'm distracted by other
things.

Overall, these characteristics: win 8.1. , Nodejs 5.1 or 4.x, python 2.7,
and set msvs 2012

2015-12-03 21:38 GMT+05:00 m1k3 <notifications@github.com>:

> Weird. Can you tell me more about your system? Nodejs version, OS version,
> msvc version...
> We test node-webgl and node-glfw on mac, linux, windows. For windows, we
> use nodejs 4.x, latest Nan and bindings, latest release of glfw3,
> AntTweakBar, GLEW and latest AMD APP SDK or nvidia and respective drivers.
>
> --mike
>
>
>
> On Wed, Dec 2, 2015 at 10:30 PM -0800, "NickLatysh" <
> notifications@github.com<mailto:notifications@github.com>> wrote:
>
> For whatever reasons, the garbage MSVC gives a lot of errors and does not
> allow to install the module as expected. On GitHub to some projects in the
> instructions given version that will suit most often have to do a fall.
>
> --Nick
>
> 2015-12-03 0:18 GMT+05:00 m1k3 <notifications@github.com>:
>
> > Not really. Your js code will continue working but internal changes
> > between node 0.8 and 3+ are so big that it would be too painful to
> maintain.
> > Out of curiosity, why do u need to use such an outdated version of node?
> >
> > --mike
> >
> >
> >
> > On Wed, Dec 2, 2015 at 5:56 AM -0800, "NickLatysh" <
> > notifications@github.com<mailto:notifications@github.com>> wrote:
> >
> >
> > You can downgrade ? if use node 0.8.9 september 2015 version, you can
> make
> > the module using the node-gyp
> >
> > -
> > Reply to this email directly or view it on GitHub<
> > https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161300168
> >.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161403717>
> > .
> >
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161530580>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161709363>
> .
>

-

**Comment by mikeseven** [comment]
Btw, don't forget to do
npm install bindings nan --save
In the directory of node-glfw and node-webgl.

--mike



On Thu, Dec 3, 2015 at 7:16 PM -0800, "NickLatysh" <notifications@github.com<mailto:notifications@github.com>> wrote:

Mike, do not want to puff your brains out, now I'm distracted by other
things.

Overall, these characteristics: win 8.1. , Nodejs 5.1 or 4.x, python 2.7,
and set msvs 2012

2015-12-03 21:38 GMT+05:00 m1k3 <notifications@github.com>:

> Weird. Can you tell me more about your system? Nodejs version, OS version,
> msvc version...
> We test node-webgl and node-glfw on mac, linux, windows. For windows, we
> use nodejs 4.x, latest Nan and bindings, latest release of glfw3,
> AntTweakBar, GLEW and latest AMD APP SDK or nvidia and respective drivers.
>
> --mike
>
>
>
> On Wed, Dec 2, 2015 at 10:30 PM -0800, "NickLatysh" <
> notifications@github.com<mailto:notifications@github.com>> wrote:
>
> For whatever reasons, the garbage MSVC gives a lot of errors and does not
> allow to install the module as expected. On GitHub to some projects in the
> instructions given version that will suit most often have to do a fall.
>
> --Nick
>
> 2015-12-03 0:18 GMT+05:00 m1k3 <notifications@github.com>:
>
> > Not really. Your js code will continue working but internal changes
> > between node 0.8 and 3+ are so big that it would be too painful to
> maintain.
> > Out of curiosity, why do u need to use such an outdated version of node?
> >
> > --mike
> >
> >
> >
> > On Wed, Dec 2, 2015 at 5:56 AM -0800, "NickLatysh" <
> > notifications@github.com<mailto:notifications@github.com>> wrote:
> >
> >
> > You can downgrade ? if use node 0.8.9 september 2015 version, you can
> make
> > the module using the node-gyp
> >
> > -
> > Reply to this email directly or view it on GitHub<
> > https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161300168
> >.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161403717>
> > .
> >
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161530580>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeseven/node-webgl/issues/23#issuecomment-161709363>
> .
>

-
