### ISSUE TITLE
iojs/nodev0.12 issue with threejs

### ISSUE THREAD

**Issue by jhludwig** [mikeseven/node-webgl#36]
(pulling this up from https://github.com/mikeseven/node-webgl/pull/35).

I have been using threejs as modified for node by kabbi (https://github.com/kabbi/three.js).  This works great with ubuntu standard node, v0.10.25.  kabbi has provided some examples in his three.js project in the examples-nwgl directory that all work well.

i am now trying to move to current node or iojs.  iojs 1.6.2, node v012.x.  in both cases, the examples fail with the following error:

```
/home/john/ws/var/release/install/bin/hostjs/node_modules/node-webgl/lib/webgl.js:1004
  return _uniformMatrix4fv(location ? location._ : 0, transpose, value);
         ^
Error: Not enough data for UniformMatrix4fv
    at Error (native)
    at Object.uniformMatrix4fv (/home/john/ws/var/release/install/bin/hostjs/node_modules/node-webgl/lib/webgl.js:1004:10)
    at loadUniformsGeneric (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:22802:10)
    at setProgram (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:22248:4)
    at renderBufferDirect (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:20158:17)
    at renderObjects (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:21197:11)
    at render (/home/john/ws/var/release/install/bin/hostjs/node_modules/three/three.js:21070:4)
    at render (/home/john/ws/var/release/install/bin/hostjs/example3/example-cube.js:29:11)
    at Object.<anonymous> (/home/john/ws/var/release/install/bin/hostjs/example3/example-cube.js:32:1)
```

this error is originating from webgl.cc in the NAN_METHOD UniformMatrix4fv, line 377: 
```
NAN_METHOD(UniformMatrix4fv) {
  NanScope();

  GLint location = args[0]->Int32Value();
  GLboolean transpose = args[1]->BooleanValue();
  GLsizei count=0;
  GLfloat* data=getArrayData<GLfloat>(args[2],&count);

  if (count < 16) {
    NanThrowError("Not enough data for UniformMatrix4fv");
  }
```
it occurs because the uniform matrix does not appear to have enough data.  on the javascript side, it is easy to use node-debug to inspect and see that the javascript array does indeed have the requisite 16 elements, but for some reason webgl.cc is not seeing.

the count variable comes from line 374, which is expanded inline by lines 72-89.  arg is an object in this case, so num and data are extracted in lines 84/85:
```
    else if(arg->IsObject()) {
      if(num) *num = arg->ToObject()->GetIndexedPropertiesExternalArrayDataLength();
      data = reinterpret_cast<Type*>(arg->ToObject()->GetIndexedPropertiesExternalArrayData());
    }
```

  this is as far as i have tracked the problem.  

now i am a total v8 noob, but in surfing around i see that there have been some changes in external objects in the latest versions of node and iojs.  this particular discussion seemed interesting to me https://github.com/rvagg/nan/issues/291, again tho i am pretty ignorant about v8 as of yet.  but it seems like this thread may be suggesting a different way to access external objects?

will post more here as i learn more.  i have slickedit/gdb hooked up with the c++ side if i can provide any more data

**Comment by jhludwig** [comment]
btw, a simple repro is lesson08.js in the test dir of this project.

**Comment by jhludwig** [comment]
see the discussion at https://github.com/iojs/io.js/issues/1353 for a proposal on how to fix.  i was going to take a whack at, tho i am a bit of a bumbler yet wrt v8.  if someone more competent than me wants to take on...

**Comment by jhludwig** [comment]
OK i have a working build on iojs.  i will prep a pull request.  a question for you is how you want to handle versioning.  i am starting to see projects increment versions and only support node v12/iojs with new versions.  i personally have no need for builds supporting node v0.10.x and would be happy not to test with but defer to maintainers.

**Comment by mikeseven** [comment]
yes agree, I think it’s time to move to 0.12!

— mike

**Comment by mikeseven** [comment]
Now that node4/nan2 support is in, this three.js should work with node-webgl. Can u try?

**Comment by mikeseven** [comment]
i tried, it works with kabbi/three.js and left a note for kabbi to change his code in utils/build/node.three.js/package.json, to refer to node-webgl >=0.5.0 or *, which you can also do in his package... and samples work ;-)
