### ISSUE TITLE
Fail install

### ISSUE THREAD

**Issue by tommyZZM** [mikeseven/node-webgl#40]
v8
  ::String”的声明
..\src\atb.cc(39): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\glfw.cc(86): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_
MyWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
..\src\atb.cc(39): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\glfw.cc(86): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_
GameDev
lope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\g
lfw.vcxproj]
..\src\atb.cc(39): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\glfw.cc(89): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_My
WorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(40): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\glfw.cc(89): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_
MyWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
..\src\atb.cc(40): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\glfw.cc(89): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_
GameDev
lope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\g
lfw.vcxproj]
..\src\atb.cc(40): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\glfw.cc(90): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_My
WorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(41): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\glfw.cc(90): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_
MyWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
..\src\atb.cc(41): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\glfw.cc(90): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_
GameDev
lope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\g
lfw.vcxproj]
..\src\atb.cc(41): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\glfw.cc(93): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_My
WorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(42): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\glfw.cc(93): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_
MyWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
..\src\atb.cc(42): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\glfw.cc(93): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_
GameDev
lope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\g
lfw.vcxproj]
..\src\atb.cc(42): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\glfw.cc(94): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_My
WorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(44): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\glfw.cc(94): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_
MyWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
..\src\atb.cc(44): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\glfw.cc(94): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_
GameDev
lope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\g
lfw.vcxproj]
..\src\atb.cc(44): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\glfw.cc(95): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_My
WorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(45): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\glfw.cc(95): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_
MyWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
..\src\atb.cc(45): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\glfw.cc(95): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_
GameDev
lope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\g
lfw.vcxproj]
..\src\atb.cc(45): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\glfw.cc(98): error C2664: “v8::Local<v8::Array> v8::Array::New(v8::Isola

te *,int)”: 无法将参数 1 从“int”转换为“v8::Isolate *” [E:\_MyWorkSpace\_Gam
eDevlope\Test
\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\glfw.vcxpr
oj]
          从整型转换为指针类型要求 reinterpret_cast、C 样式转换或函数样式转换
..\src\atb.cc(46): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\glfw.cc(100): error C2660: “v8::Object::New”: 函数不接受 0 个参数 [E:\_
MyWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
..\src\atb.cc(46): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\glfw.cc(101): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_M
yWorkSpa
ce\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-g
lfw\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(46): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\glfw.cc(101): fatal error C1003: 错误计数超过 100；正在停止编译 [E:\_MyWo
rkSpace\_Gam
eDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\bui
ld\glfw.vcxproj]
..\src\atb.cc(47): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(47): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\atb.cc(47): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\atb.cc(48): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(48): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\atb.cc(48): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\atb.cc(49): error C2039: “NewSymbol”: 不是“v8::String”的成员 [E:\_MyW
orkSpace
\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glf
w\build\glfw.vcxproj]
          C:\Users\tommyZZM\.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : 参见“
v8
  ::String”的声明
..\src\atb.cc(49): error C2660: “v8::Integer::New”: 函数不接受 1 个参数 [E:\_M
yWorkSpac
e\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-gl
fw\build\glfw.vcxproj]
..\src\atb.cc(49): error C3861: “NewSymbol”:  找不到标识符 [E:\_MyWorkSpace\_G
ameDevl
ope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build\gl
fw.vcxproj]
..\src\atb.cc(49): fatal error C1003: 错误计数超过 100；正在停止编译 [E:\_MyWork
Space\_GameD
evlope\Test\HelloNodeWebGL\node_modules\node-webgl\node_modules\node-glfw\build
\glfw.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\DigitalMedia\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\DigitalMedia\\nodejs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\_MyWorkSpace\_GameDevlope\Test\HelloNodeWebGL\node_modules\node-
webgl\node_modules\node-glfw
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\DigitalMedia\\nodejs\\\\node.exe" "D:\\DigitalMedia\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! node-glfw@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-glfw@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-glfw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-glfw
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\_MyWorkSpace\_GameDevlope\Test\HelloNodeWebGL\npm-debug.log

**Comment by pnispel** [comment]
getting the same error here.

**Comment by pnispel** [comment]
changing my node version to 10.38 fixed the issue
