### ISSUE TITLE
Three.js npm node for node-webcl and node-webgl 

### ISSUE THREAD

**Issue by waqasm86** [mikeseven/node-webgl#41]
Hello Mike, 
                    I have been following your repository for quite a while. I was curious if you can create an npm node for three.js regarding node-webcl and node-webgl compatible. I am also waiting for node-glfw for node v0.12.x.

Thanks you

Waqas

**Comment by mikeseven** [comment]
Thanks for interest.
Three.js should work with node-webgl. I have not tried in a long long time though. Now that node4/nan2 is in, let's try!

**Comment by mikeseven** [comment]
i tried, it works with kabbi/three.js and left a note for kabbi to change his code in utils/build/node.three.js/package.json, to refer to node-webgl >=0.5.0 or *, which you can also do in his package... and samples work ;-)
