### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by HMUDesign** [mikeseven/node-webgl#44]
There seems to be a lack of support for anti-aliasing. (Would this be better on node-glfw?)

I am testing this on windows 10 with the latest of all the dependencies, all 64-bit.

If this should be working, let me know what I can do to help figure it out. If this is just a lacking from core libraries that we have no control over, let me know. =]

**Comment by mikeseven** [comment]
this should be configured when GLFW window is created.
I only use default settings and, for speed, it’s probably not turned on.

On Nov 22, 2015, at 7:53 PM, Christopher Baker <notifications@github.com<mailto:notifications@github.com>> wrote:


There seems to be a lack of support for anti-aliasing. (Would this be better on node-glfw?)

I am testing this on windows 10 with the latest of all the dependencies, all 64-bit.

If this should be working, let me know what I can do to help figure it out. If this is just a lacking from core libraries that we have no control over, let me know. =]

**Comment by HMUDesign** [comment]
Alright. For anybody else looking for this, you need to include `GLFW.WindowHint(GLFW.SAMPLES, 4);` in the createWindow method of /lib/platform_glfw.js, before the call to `GLFW.CreateWindow`. I am working on an easier way to access this functionality, but for now this is the best I have. =]
